# Generated by Django 5.0.3 on 2024-03-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='actors',
            field=models.ManyToManyField(blank=True, related_name='plays', to='theatre.actor'),
        ),
        migrations.AlterField(
            model_name='play',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='plays', to='theatre.genre'),
        ),
    ]
