# Generated by Django 5.0.3 on 2024-03-27 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0003_alter_theatrehall_rows_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['row', 'seat']},
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('performance', 'row', 'seat')},
        ),
    ]
